version: "3.9"
services:
  web:
    labels:
      shipyard.route: '/'
    build:
      context: .
      args:
        - TEST_ARG=${TEST_ARG}
        - REDIS_URL=${SHIPYARD_DOMAIN_REDIS}
    ports:
      - '80'
    environment:
      CI: 'true'
      CII: 'false'
  db:
    image: 'postgres:9.6-alpine'
    labels:
      shipyard.init: "chown -R 10001:10001 /var/lib/postgresql/data/pgdata"
      shipyard.init.container: "true"
      shipyard.init.container.image: busybox
    environment:
      POSTGRES_USER: 'obscure-user'
      POSTGRES_PASSWORD: 'obscure-password'
      POSTGRES_DB: 'app'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432'

  migration:
    build: .
    depends_on:
      - db
    restart: "no"  # Prevent infinite restarts

volumes:
  postgres:
